### ISSUE TITLE
Error in Integration Test contacts.test.js

### ISSUE THREAD

**Issue by jdhunt** [robert52/mean-blueprints-cm#1]
Line 11 in mean-blueprints-cm/tests/integration/contacts.test.js causes an error when running with mocha:
`const userFixture = require('../fixtures/user');`

../fixtures/user does not exist.

**Comment by lucaseverett** [comment]
The tests/fixtures folder is listed in .gitignore.

**Comment by robert52** [comment]
Hi!

@jdhunt are listed in the ignore file as @lucaseverett pointed out, because technically the `fixtures` contain also user sensitive data such as the `password hash` and `salt`. 

I'll push some changes that will contain a `seed` module which will generate fixtures for the app. That should solve the problem.

**Comment by robert52** [comment]
I've create a small helper seed file, that will create the necessary fixture file. The following command in the project's folder should do the trick:

``` bash
$ node seeds/user.fixture.js
```

This will create a file called `/tests/fixtures/user.js` with all the necessary data.
